version: '3.8'

services:
  api:
    container_name: CoM-api
    image: ghcr.io/gabinrn/count-of-money-api:main
    volumes:
      - ../backend:/api
    ports:
      - "4000:4000"
    environment:
        JWTSECRET: ${JWTSECRET}
        MONGODB_URI: ${MONGODB_URI}
    
  front:
    container_name: CoM-front
    image: ghcr.io/gabinrn/count-of-money-front:main
    volumes:
      - ../frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - api